project:
  type: website

website:
  title: "Applied AI notes for everyone"
  site-url: https://shekibahmed.github.io/knowledge-journal
  repo-url: https://github.com/shekibahmed/knowledge-journal
  repo-actions: [edit, issue]
  navbar:
    logo: images/logo.png
    background: primary
    search: true
    left:
      - href: index.md
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/shekibahmed/knowledge-journal
      - icon: rss
        aria-label: RSS
        href: index.xml
  page-footer:
    left: "© 2025 Knowledge Journal"
    right:
      - icon: rss
        text: RSS
        href: index.xml

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    page-layout: article
    css: styles.css
    code-copy: true

metadata:
  twitter-card: true
  open-graph: true
  image: images/logo.png

execute:
  freeze: auto
