# git-cliff configuration for Knowledge Journal changelog generation

[git]
tag_pattern = "^v[0-9].*"
conventional_commits = true
filter_unconventional = false
protect_breaking_commits = true

date_order = true

commit_parsers = [
  { pattern = "^feat", group = "Features" },
  { pattern = "^fix", group = "Fixes" },
  { pattern = "^docs", group = "Documentation" },
  { pattern = "^perf", group = "Performance" },
  { pattern = "^test", group = "Tests" },
  { pattern = "^build", group = "Build" },
  { pattern = "^ci", group = "CI" },
  { pattern = "^refactor", group = "Refactors" },
  { pattern = "^style", group = "Styling" },
  { pattern = "^chore", group = "Chores" },
  { pattern = "^revert", group = "Reverts" },
  { pattern = ".*", group = "Other" }
]

commit_preprocessors = [
  { pattern = "Co-authored-by:.*", replace = "" }
]

[changelog]
unreleased = true
header = """
# Changelog

All notable changes to this project will be documented in this file. The format
is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) and this
project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""

description = "Generated automatically with git-cliff."

body = """
{% if version %}## [{{ version | trim_start_matches(pat="v") }}] - {{ date | date(format="%Y-%m-%d") }}{% else %}## [Unreleased]{% endif %}

{% if commits | filter(attribute="group") | length > 0 %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }} ([{{ commit.hash | truncate(length=7) }}]({{ commit.links.commit }}))
{% endfor %}
{% endfor %}
{% else %}
- No changes recorded.
{% endif %}
"""

footer = """
<!-- generated by git-cliff -->
"""

trim = true
