name: Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: changelog-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          output: CHANGELOG.md
          args: --unreleased

      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "docs: update changelog"
          file_pattern: CHANGELOG.md
