name: make-site
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build and preview site
        run: |
          pip install jupyter nbconvert
          bundle install
          bundle exec jekyll build --trace